vim.keymap.set("n", "<leader>l", "<cmd>Lazy<cr>")
vim.keymap.set("n", "<esc>", "<cmd>noh<cr>", { desc = "noh", noremap = true, silent = true })
vim.keymap.set("n", "<leader>cn", "<cmd>Noice<cr>", { desc = "Noice" })
vim.keymap.set("n", "H", "<cmd>bprevious<cr>")
vim.keymap.set("n", "L", "<cmd>bnext<cr>")
